### ISSUE TITLE
Let's talk routing and metrics

### ISSUE THREAD

**Issue by davidascher** [MozillaFoundation/mofo-example-app#35]
This probably needs to have an equivalent issue in https://github.com/MozillaFoundation/MoFo-Engineering-Handbook but there's an implementation question as well, and we may want to start w/ a PoC and then write it up.

There is a gradient between single-page apps and heavy transitions between pages with full page loads.  React makes it easy to do the former, and pushState makes it possible to have the advantages of single-pageness (in particular responsiveness) while keeping bookmarkability and meaningful URLs).  We need a golden path that we agree to use for this, especially as more often than not we'll also want to understand the user flows through those transitions, meaning GA-style metrics.  Thus, I think we need both:

 * a routing implementation choice (there lay some dragons, as the mental model takes some getting used to).  e.g. https://github.com/rackt/react-router
 * likely some mixins or components to facilitate the GA integration, so that the right magical thing happens in the GA funnels, etc.

There are interesting and challenging questions about how this works in an offline Cordova hosted app as well.

/cc @adamlofting @Pomax @simonwex @thisandagain @k88hudson

**Comment by adamlofting** [comment]
Thanks for filing. This has been on my mind too. I will spend a bit more time playing with the example app and getting to grips with React in the coming days.

Next week I want to dig into the instrumentation for WMA which will give us better grounding for this.

For reference: This is the corresponding issue in the handbook: https://github.com/MozillaFoundation/MoFo-Engineering-Handbook/issues/12

**Comment by adamlofting** [comment]
To note: we have an example implementation of pageview tracking alongside `react-router` in the teach site now: https://github.com/mozilla/teach.webmaker.org/blob/develop/lib/routes.jsx#L102

That site, and the example app work a little differently to each other but I'm hoping to find a more generic way to implement this that works regardless of how we use React.

**Comment by toolness** [comment]
We've been using `react-router` on the Teach site and I *generally* like it, with the particular exception that testing components which use `react-router` components is [a huge pain](https://github.com/rackt/react-router/blob/master/docs/guides/testing.md). The library also uses an as-of-yet undocumented feature of React called [react contexts](https://www.tildedave.com/2014/11/15/introduction-to-contexts-in-react-js.html) which makes them a bit confusing to understand conceptually.

That said, one of the particular things I like about `react-router` is that it fully supports JSX rendered on the server/buildtool-side, which is a big use case for the teach site (since teach is just a website and not a web app, we're trying to embrace progressive enhancement to make the site content as accessible as possible). It also exposes the "normalized" URL in a very straightforward way, which makes page tracking easier, regardless of whether the underlying implementation is using pushState or URL fragment identifiers or something else.

**Comment by adamlofting** [comment]
Here is our documentation on using `react-ga` with `react-router`: https://github.com/adamlofting/react-ga#initializing-ga--and-tracking-pageviews-with-react-router

Currently in use on teach.mozilla.org, and id.webmaker.org
